spec:
  structures:
    - buttons
  label: Button

blueprint:
  importance: 1
  label:
  href:

preview:

_inputs:
  importance:
    type: choice
    options:
      values:
        - 1
        - 2
        - 3
#