spec:
  structures:
    - buttons
  label: Button

blueprint:
  importance:
  importance2:
  label:
  href:

preview:

_inputs:
  importance:
    type: choice
    options:
      values:
        - 1
        - 2
        - 3
  importance2:
    type: choice
    options:
      values:
        - '1'
        - '2'
        - '3'
#