products:
  card:
    frame: panel
    look: surface
    hue: base
    scheme: dark
    class: '[&_p]:hidden'
  image:
    position: cover
    ratio: square
posts:
  card:
    frame: panel
    look: surface
    hue:
    scheme:
  image:
    position:
    ratio:
    class: mask
services:
  card:
    frame: panel
    look: surface
    hue:
    scheme:
    class: justify-end
  image:
    position: background
    ratio: landscape
    class: mask-lg
reviews:
  card:
    frame: panel
    look: surface
    hue:
    scheme:
  image:
    position: 
    ratio: square
    class: mask
categories:
  card:
    frame: panel
    look: surface
    hue:
    scheme:
  image:
    position:
    ratio:
persons:
  card:
    frame: ghost
    look: surface
    hue:
    scheme:
  image:
    position:
    ratio:
features:
  card:
    frame: fill
    look:
    hue:
    scheme:
  icon:
    hue:
    ratio:
    importance: tertiary
    layout:
highlights:
  card:
    frame: panel
    look: surface
    hue:
    scheme:
  image:
    position:
    ratio:
offers:
  card:
    frame: panel
    look: surface
    hue:
    scheme:
  segment:
    class: h-full
  group:
    importance:
    layout: col
    class: mt-auto w-full
