_schema: intro

spec:
  structures:
    - content_blocks
  label: Intro

blueprint:
  writeup:

preview:
  writeup: |
    <h1>Lorem ipsum dolor sit</h1>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Suscipit, numquam!</p>

config:
  section:
    frame: float
    look: outline
    size:
    hue:
    scheme:
  segment:
    layout:
    align:

_inputs:
