_schema: products

spec:
  structures:
    - content_blocks
  label: Products

blueprint:
  writeup:
  buttons:
  products:

preview:
  writeup: |
    <h2>Lorem ipsum dolor sit</h2>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Suscipit, numquam!</p>
  buttons:
    - label: Lorem ipsum
      href: '#'
  products:
    - path/to/entry

config:
  section:
    align: between
    size:
  segment:
    layout: row
    align: center
  group:
    importance: tertiary
    layout: row
  deck:
    layout: carousel
    size: