paths:
  data: src/data
  static: src/assets/uploads
  uploads: src/assets/uploads

# -----------------------------------------------
# Cloudcannn sidebar configuration
# -----------------------------------------------

collection_groups:
  - heading: Pages
    collections:
      - pages
      - services
      - posts
      - products
      - categories
      - policies
  - heading: Shared
    collections:
      - reviews
      - persons
      - forms
      - data
  - heading: Config
    collections:
      - elements
      - cards
      - blocks

# -----------------------------------------------
# Collection configuration
# -----------------------------------------------

collections_config:

  pages:
    path: src/content/pages
    url: /[full_slug]/
    output: true
    icon: wysiwyg
    disable_add_folder: true
    _enabled_editors:
      - visual
    schemas: 
      default: 
        path: src/content/pages/_pages.md

  services:
    path: src/content/services
    url: /diensten/[full_slug]/
    output: true
    icon: home_repair_service
    disable_add_folder: true
    _enabled_editors:
      - visual
    schemas: 
      default: 
        path: src/content/services/_services.md

  products:
    path: src/content/products
    url: /producten/[full_slug]/
    output: true
    icon: shopping_cart
    disable_add_folder: true
    _enabled_editors:
      - content
      - data
    schemas: 
      default: 
        path: src/content/products/_products.md

  categories:
    path: src/content/categories
    url: /categorieen/[full_slug]/
    output: true
    icon: category
    disable_add_folder: true
    _enabled_editors:
      - data
    schemas: 
      default: 
        path: src/content/categories/_categories.md
        
  posts:
    path: src/content/posts
    url: /posts/[full_slug]/
    output: true
    icon: edit_document
    disable_add_folder: true
    _enabled_editors:
      - content
    schemas: 
      default: 
        path: src/content/posts/_posts.md

  policies:
    path: src/content/policies
    url: /beleid/[full_slug]/
    output: true
    icon: policy
    disable_add_folder: true
    _enabled_editors:
      - content
    schemas: 
      default: 
        path: src/content/policies/_policies.md

  reviews:
    path: src/content/reviews
    output: false
    icon: reviews
    disable_add_folder: true
    _enabled_editors:
      - data
    schemas: 
      default: 
        path: src/content/reviews/_reviews.md
        
  persons:
    path: src/content/persons
    output: false
    icon: diversity_3
    disable_add_folder: true
    _enabled_editors:
      - data
    schemas: 
      default: 
        path: src/content/persons/_persons.md

  forms:
    path: src/content/forms
    output: false
    icon: dynamic_form
    disable_add_folder: true
    _enabled_editors:
      - data
    schemas: 
      default: 
        path: src/content/forms/_forms.md

  data:
    path: src/data
    output: false
    icon: 
    _enabled_editors:
      - data
    disable_file_actions: true
    disable_add_folder: true
    disable_add: true
    schemas:
      theme: 
        path: src/data/theme.yml
      layout: 
        path: src/data/layout.yml
      company: 
        path: src/data/company.yml

  blocks:
    path: src/components/blocks
    url: /blocks/[full_slug]/
    output: true
    disable_file_actions: true
    disable_add_folder: true
    disable_add: true
    _enabled_editors:
      - visual
    schemas:
      categories:
        path: src/components/blocks/categories.bookshop.yml
      contact:
        path: src/components/blocks/contact.bookshop.yml
      content:
        path: src/components/blocks/content.bookshop.yml
      cta:
        path: src/components/blocks/cta.bookshop.yml
      highlights:
        path: src/components/blocks/highlights.bookshop.yml
      features:
        path: src/components/blocks/features.bookshop.yml
      hero:
        path: src/components/blocks/hero.bookshop.yml
      spotlight:
        path: src/components/blocks/spotlight.bookshop.yml
      intro:
        path: src/components/blocks/intro.bookshop.yml
      offers:
        path: src/components/blocks/offers.bookshop.yml
      persons:
        path: src/components/blocks/persons.bookshop.yml
      posts:
        path: src/components/blocks/posts.bookshop.yml
      products:
        path: src/components/blocks/products.bookshop.yml
      reviews:
        path: src/components/blocks/reviews.bookshop.yml  
      services:
        path: src/components/blocks/services.bookshop.yml  

  cards:
    path: src/components/cards
    url: /cards/[full_slug]/
    output: true
    disable_file_actions: true
    disable_add_folder: true
    disable_add: true
    _enabled_editors:
      - visual
    schemas:
      categories:
        path: src/components/cards/categories.bookshop.yml
      features:
        path: src/components/cards/features.bookshop.yml
      offers:
        path: src/components/cards/offers.bookshop.yml
      persons:
        path: src/components/cards/persons.bookshop.yml
      posts:
        path: src/components/cards/posts.bookshop.yml
      products:
        path: src/components/cards/products.bookshop.yml
      reviews:
        path: src/components/cards/reviews.bookshop.yml  
      services:
        path: src/components/cards/services.bookshop.yml

  elements:
    path: src/components/elements
    url: /elements/[full_slug]/
    output: true
    disable_file_actions: true
    disable_add_folder: true
    disable_add: true
    _enabled_editors:
      - visual
    schemas:
      button:
        path: src/components/elements/buttonbutton.bookshop.yml
      channel:
        path: src/components/elements/channel/channel.bookshop.yml
      icon:
        path: src/components/elements/icon/icon.bookshop.yml
      image:
        path: src/components/elements/image/image.bookshop.yml
      input:
        path: src/components/elements/input/input.bookshop.yml
      link:
        path: src/components/elements/link/link.bookshop.yml
      prose:
        path: src/components/elements/prose/prose.bookshop.yml  
      rating:
        path: src/components/elements/rating/rating.bookshop.yml  
      select:
        path: src/components/elements/select/select.bookshop.yml
      social:
        path: src/components/elements/social/social.bookshop.yml
      textarea:
        path: src/components/elements/textarea/textarea.bookshop.yml  
      writeup:
        path: src/components/elements/writeup/writeup.bookshop.yml
        
# -----------------------------------------------
# Input customization
# -----------------------------------------------

_inputs:
  seo:
    label: SEO
    comment: Search engine optimization

  seo.title:
    label: Meta title
    comment: Aim for 50-60 characters

  seo.description:
    label: Meta description
    comment: Aim for 50-120 characters

  seo.image:
    label: Page image
    comment: Displayed when sharing a link to this page

  seo.noindex:
    label: Noindex
    comment: Prevent search engines from indexing this page

  seo.canonical:
    label: Canonical URL
    comment: The preferred URL for this page, meaning the url search engines will index, instead of the current one

  src:
    type: image
    label: Upload
    correct_orientation: false

  alt:
    label: Description

  href:
    type: url
    label: Link

# -----------------------------------------------
# Design inputs
# -----------------------------------------------

  hue:
    type: choice
    options:
      values:
        - base
        - brand
        - accent
  scheme:
    type: choice
    options:
      values:
        - light
        - dark
  size:
    type: choice
    options:
      values:
        - small
        - medium
        - large
  layout:
    type: choice
    options:
      values:
        - col
        - row
  order:
    type: choice
    options:
      values:
        - switch
        - reverse
  image.position:
    type: choice
    options:
      values:
        - relative
        - background
        - cover
  image.orientation:
    type: choice
    options:
      values:
        - square
        - landscape
        - portrait
  class:
    type: textarea

# -----------------------------------------------
# Blocks collection inputs
# -----------------------------------------------

  align:
    type: choice
    options:
      values:
        - start
        - center
        - end
  frame:
    type: choice
    options:
      values:
        - fill
        - float
        - panel
        - screen
  look:
    type: choice
    options:
      values:
        - ghost
        - outline
        - soft
        - surface
        - solid
  image.ratio:
    type: choice
    options:
      values:
        - landscape
        - square
        - portrait
  deck.layout:
    type: choice
    options:
      values:
        - carousel
        - grid
        - masonry
        - row
  group.importance:
    type: choice
    options:
      values:
        - primary
        - secondary
        - tertiary

# -----------------------------------------------
# elements to singular
# -----------------------------------------------
  button: &singular
    type: object
  link: *singular
  image: *singular
  icon: *singular
  input: *singular
  select: *singular
  textarea: *singular
  channel: *singular
  social: *singular
  rating: *singular
  visual: *singular
  asset: *singular


  writeup:
    type: html
  prose:
    type: html

  blueprint:
    hidden: true
  spec: 
    hidden: true