paths:
  data: src/data
  static: public
  uploads: public/uploads

# -----------------------------------------------
# Cloudcannn sidebar configuration
# -----------------------------------------------

collection_groups:
  - heading: Content
    collections:
      - pages
      - services
      - posts
      - products
      - categories
  - heading: Data
    collections:
      - reviews
      - persons
      - forms
      - policies
  - heading: Config
    collections:
      - globals
      - blocks

# -----------------------------------------------
# Collection configuration
# -----------------------------------------------

collections_config:

  pages:
    path: src/content/pages
    url: /[full_slug]/
    output: true
    icon: wysiwyg
    disable_add_folder: true
    _enabled_editors:
      - visual
    schemas: 
      default: 
        path: schemas/page.md

  services:
    path: src/content/services
    url: /diensten/[full_slug]/
    output: true
    icon: home_repair_service
    disable_add_folder: true
    _enabled_editors:
      - visual
    schemas: 
      default: 
        path: schemas/service.md

  products:
    path: src/content/products
    url: /producten/[full_slug]/
    output: true
    icon: shopping_cart
    disable_add_folder: true
    _enabled_editors:
      - content
      - data
    schemas: 
      default: 
        path: schemas/product.md

  categories:
    path: src/content/categories
    url: /categorieen/[full_slug]/
    output: true
    icon: category
    disable_add_folder: true
    _enabled_editors:
      - data
    schemas: 
      default: 
        path: schemas/category.md
        
  posts:
    path: src/content/posts
    url: /posts/[full_slug]/
    output: true
    icon: edit_document
    disable_add_folder: true
    _enabled_editors:
      - content
    schemas: 
      default: 
        path: schemas/posts.md

  policies:
    path: src/content/policies
    url: /beleid/[full_slug]/
    output: true
    icon: policy
    disable_add_folder: true
    _enabled_editors:
      - content
    schemas: 
      default: 
        path: schemas/policy.md

  reviews:
    path: src/content/reviews
    output: false
    icon: reviews
    disable_add_folder: true
    _enabled_editors:
      - data
    schemas: 
      default: 
        path: schemas/review.md
        
  persons:
    path: src/content/persons
    output: false
    icon: diversity_3
    disable_add_folder: true
    _enabled_editors:
      - data
    schemas: 
      default: 
        path: schemas/person.md

  forms:
    path: src/content/forms
    output: false
    icon: dynamic_form
    disable_add_folder: true
    _enabled_editors:
      - data
    schemas: 
      default: 
        path: schemas/form.md

  globals:
    path: src/content/settings
    output: false
    icon: 
    _enabled_editors:
      - data
    disable_add_folder: true
    # disable_add: true
    # disable_file_actions: true
    schemas:
      theme: 
        path: schemas/globals/theme.yml
      elements: 
        path: schemas/globals/elements.yml
      cards: 
        path: schemas/globals/cards.yml
      layout: 
        path: schemas/globals/layout.yml
      company: 
        path: schemas/globals/company.yml

  blocks:
    path: src/content/blocks
    url: /blocks/[full_slug]/
    output: true
    disable_add_folder: true
    _enabled_editors:
      - visual
    schemas:
      categories:
        path: schemas/blocks/categories.yml
      contact:
        path: schemas/blocks/contact.yml
      content:
        path: schemas/blocks/content.yml
      cta:
        path: schemas/blocks/cta.yml
      custom:
        path: schemas/blocks/custom.yml
      features:
        path: schemas/blocks/features.yml
      hero:
        path: schemas/blocks/hero.yml
      highlight:
        path: schemas/blocks/highlight.yml
      intro:
        path: schemas/blocks/intro.yml
      offers:
        path: schemas/blocks/offers.yml
      persons:
        path: schemas/blocks/persons.yml
      posts:
        path: schemas/blocks/posts.yml
      products:
        path: schemas/blocks/products.yml
      reviews:
        path: schemas/blocks/reviews.yml  
      services:
        path: schemas/blocks/services.yml  
        
# -----------------------------------------------
# Input customization
# -----------------------------------------------

_inputs:
  seo:
    label: SEO
    comment: Search engine optimization

  seo.title:
    label: Meta title
    comment: Aim for 50-60 characters

  seo.description:
    label: Meta description
    comment: Aim for 50-120 characters

  seo.image:
    label: Page image
    comment: Displayed when sharing a link to this page

  seo.noindex:
    label: Noindex
    comment: Prevent search engines from indexing this page

  seo.canonical:
    label: Canonical URL
    comment: The preferred URL for this page, meaning the url search engines will index, instead of the current one

  image.src:
    type: image
    label: Upload
    correct_orientation: false

  image.alt:
    label: Description

  src:
    type: image
    label: Upload
    correct_orientation: false

  alt:
    label: Description

  href:
    type: url
    label: Link

  writeup:
    type: html

  prose:
    type: html

# -----------------------------------------------
# Design inputs
# -----------------------------------------------

  hue:
    type: choice
    options:
      values:
        - base
        - brand
        - accent
  scheme:
    type: choice
    options:
      values:
        - light
        - dark
  size:
    type: choice
    options:
      values:
        - small
        - medium
        - large
  layout:
    type: choice
    options:
      values:
        - col
        - row
  order:
    type: choice
    options:
      values:
        - switch
        - reverse
  image.position:
    type: choice
    options:
      values:
        - relative
        - background
        - cover
  image.orientation:
    type: choice
    options:
      values:
        - square
        - landscape
        - portrait
  class:
    type: textarea

# -----------------------------------------------
# Blocks collection inputs
# -----------------------------------------------

  align:
    type: choice
    options:
      values:
        - start
        - center
        - end
  frame:
    type: choice
    options:
      values:
        - fill
        - float
        - panel
        - screen
  look:
    type: choice
    options:
      values:
        - ghost
        - outline
        - soft
        - surface
        - solid
  image.ratio:
    type: choice
    options:
      values:
        - landscape
        - square
        - portrait
  deck.layout:
    type: choice
    options:
      values:
        - carousel
        - grid
        - masonry
        - row
  buttons.importance:
    type: choice
    options:
      values:
        - primary
        - secondary
        - tertiary