paths:
  uploads: public/uploads
  static: public
  data: src/data
collections_config:
  pages:
    path: src/content/pages
    output: true
    url: /[full_slug]/
    description: ''
    icon: wysiwyg
    _editables: {}
    _enabled_editors:
      - data
    _inputs: {}
    _select_data: {}
    _structures: {}
    disable_add: false
    disable_add_folder: true
    disable_file_actions: false
    schemas:
      default:
        path: schemas/pages.md
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: true
        icon: notes
        _editables: {}
        _inputs: {}
        _select_data: {}
        _structures: {}
  services:
    path: src/content/services
    output: true
    url: /diensten/[full_slug]/
    icon: home_repair_service
    _enabled_editors:
      - data
    disable_add: false
    disable_add_folder: true
    disable_file_actions: false
    schemas:
      default:
        path: schemas/services.md
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: true
        icon: notes
  products:
    path: src/content/products
    output: true
    url: /producten/[full_slug]/
    icon: shopping_cart
    _enabled_editors:
      - data
    disable_add: false
    disable_add_folder: true
    disable_file_actions: false
    schemas:
      default:
        path: schemas/products.md
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: true
        icon: notes
  categories:
    path: src/content/categories
    output: true
    url: /categorieen/[full_slug]/
    icon: category
    _enabled_editors:
      - data
    disable_add: false
    disable_add_folder: true
    disable_file_actions: false
    schemas:
      default:
        path: schemas/categories.md
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: true
        icon: notes
  brands:
    path: src/content/brands
    output: true
    url: /merken/[full_slug]/
    icon: shape_line
    _enabled_editors:
      - data
    disable_add: false
    disable_add_folder: true
    disable_file_actions: false
    schemas:
      default:
        path: schemas/brands.md
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: true
        icon: notes
  posts:
    path: src/content/posts
    output: true
    url: /posts/[full_slug]/
    icon: edit_document
    _enabled_editors:
      - content
    disable_add: false
    disable_add_folder: true
    disable_file_actions: false
    schemas:
      default:
        path: schemas/posts.md
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: true
        icon: notes
  policies:
    path: src/content/policies
    output: true
    url: /beleid/[full_slug]/
    icon: policy
    _enabled_editors:
      - content
    disable_add: false
    disable_add_folder: true
    disable_file_actions: false
    schemas:
      default:
        path: schemas/policies.md
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: true
        icon: notes
  data:
    path: src/content/data
    output: false
    icon:
    disable_add: true
    disable_add_folder: true
    disable_file_actions: true
    schemas:
      theme:
        path: schemas/data/theme.yml
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: true
        icon: notes
      components:
        path: schemas/data/components.yml
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: true
        icon: notes
      company:
        path: schemas/data/company.yml
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: true
        icon: notes
  reviews:
    path: src/content/reviews
    output: false
    icon: reviews
    _enabled_editors:
      - data
    disable_add: false
    disable_add_folder: true
    disable_file_actions: false
    schemas:
      default:
        path: schemas/reviews.md
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: true
        icon: notes
  employees:
    path: src/content/employees
    output: false
    icon: diversity_3
    _enabled_editors:
      - data
    disable_add: false
    disable_add_folder: true
    disable_file_actions: false
    schemas:
      default:
        path: schemas/employees.md
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: true
        icon: notes
  forms:
    path: src/content/forms
    output: false
    icon: dynamic_form
    _enabled_editors:
      - data
    disable_add: false
    disable_add_folder: true
    disable_file_actions: false
    schemas:
      default:
        path: schemas/forms.md
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: true
        icon: notes
collection_groups:
  - heading: Pagina's
    collections:
      - pages
      - services
      - posts
      - policies
  - heading: Producten
    collections:
      - products
      - categories
      - brands
  - heading: Data
    collections:
      - reviews
      - employees
      - forms
      - data
_inputs:
  seo:
    type: auto
    label: SEO
    comment: Search engine optimization
    cascade: true
  seo.title:
    type: auto
    label: Meta title
    comment: Aim for 50-60 characters
    cascade: true
  seo.description:
    type: auto
    label: Meta description
    comment: Aim for 50-120 characters
    cascade: true
  seo.image:
    type: auto
    label: Page image
    comment: Displayed when sharing a link to this page
    cascade: true
  seo.noindex:
    type: auto
    label: Noindex
    comment: Prevent search engines from indexing this page
    cascade: true
  seo.canonical:
    type: auto
    label: Canonical URL
    comment: >-
      The preferred URL for this page, meaning the url search engines will
      index, instead of the current one
    cascade: true
  image.src:
    type: image
    label: Upload
    cascade: true
    correct_orientation: false
  image.alt:
    type: auto
    label: Description
    cascade: true
  src:
    type: image
    label: Upload
    cascade: true
    correct_orientation: false
  alt:
    type: auto
    label: Description
    cascade: true
  href:
    type: url
    label: Link
    cascade: true
  writeup:
    type: html
    cascade: true
  prose:
    type: html
    cascade: true
_select_data: {}
_structures:
  test:
    style: select
    values:
      - title:
        description:
      - test2:
        test3:
_editables: {}
data_config: {}
timezone: Etc/UTC
