# The spec section names this component and tells CloudCannon where you can place this component on your site.
spec:
  label: Button

# The blueprint section defines the data your component needs and provides the default values when a new component is created.
blueprint:
  label: Click me
  href: https://full.dev
  color: red
  look: outline


# The preview section is used in the Bookshop component browser and doesn't affect visual editing. We can ignore this key for now
preview:

# The _inputs section is passed through as CloudCannon's input configuration, allowing you to customize the fields specified in the blueprint.
_inputs:
