spec:
  structures:
    - content_blocks
  label: Custom Block

blueprint:
  posts:

preview:

setting:


_inputs:
  blueprint:
    type: object
    options:
      subtype: mutable
      entries:
        # Object keys
        allowed_keys:
          - writeup
          - buttons
          - image
          - form
          - categories
          - persons
          - posts
          - products
          - reviews
          - services
        # Object structures
        # structures: 
        #   values:
        #   - id: image
        #     label: Image
        #     value:
        #       src:
        #       alt:
        #   - id: buttons
        #     label: Buttons
        #     value:
        #       - label:
        #       - href:
        #   - id: other
        #     label: Other
        # # Structures assign to keys
        # assigned_structures:
        #   writeup:
        #     - flat
        #   buttons:
        #     - buttons
        #   image:
        #     - image
        #   form:
        #     - other
        #   categories:
        #     - other
        #   persons:
        #     - other
        #   posts:
        #     - other            
        #   products:
        #     - other
        #   reviews:
        #     - other
        #   services:
        #     - other      