spec:
  structures:
    - blocks
  label: Brands

blueprint:
  section: bookshop:wrappers/section
  segment: bookshop:wrappers/segment
  writeup: bookshop:elements/writeup
  group: bookshop:wrappers/group
  buttons:
    - bookshop:elements/button
  deck: bookshop:wrappers/deck
  brands:

preview: