# The spec section names this component and tells CloudCannon where you can place this component on your site.
spec:
  structures:
    - blocks
  label: Hero
  description: A hero component
  icon: nature_people

# The blueprint section defines the data your component needs and provides the default values when a new component is created.
blueprint:
  button: bookshop:buttonVariant

# The preview section is used in the Bookshop component browser and doesn't affect visual editing. We can ignore this key for now
preview:

# The _inputs section is passed through as CloudCannon's input configuration, allowing you to customize the fields specified in the blueprint.
_inputs:
