title: Categories

spec:
  structures:
    - content_blocks
  label: Categories

blueprint:
  writeup:
  buttons:
  categories:

config:
  section:
    align: start
    size:
  segment:
    layout: col
    align:
  buttons:
    importance: secondary
    layout: row
  deck:
    layout: carousel
    size:

_inputs:  
  blueprint:
    type: object
    options:
      subtype: mutable
      entries:
        allowed_keys:
          - writeup
          - buttons
          - categories

preview: