spec:
  structures:
    - content_blocks
  label: Custom Block

blueprint:

preview:

_inputs:
  blueprint:
    type: object
    options:
      subtype: mutable
      entries:
        structures: _structures.elements
        allowed_keys:
          - writeup
          - buttons
          - image
          - form
          - categories
          - persons
          - posts
          - products
          - reviews
          - services
        assigned_structures:
          image:
            - image
          buttons:
            - buttons
          writeup:
            - writeup

_structures:
  elements:
    values:
      - id: image
        label: Image
        value:
          src:
          alt:
      - id: buttons
        label: Buttons
        value:
          - src:
          - alt:
      - id: writeup
        label: Writeup
        value:
