title: Highlight

spec:
  structures:
    - content_blocks
  label: Highlight

blueprint:
  writeup:
  buttons:
  image: 
    src:
    alt:

preview:
  writeup: |
    <h2>Lorem ipsum dolor sit</h2>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Suscipit, numquam!</p>
  buttons:
    - label: Lorem ipsum
      href: '#'
    - label: Lorem ipsum
      href: '#'
  image:
    src: /images/img.jpeg
    alt: Lorem ipsum dolor sit

config:
  section:
    layout: row
    align: center
    frame: fill
    look:
    order:
    size:
    hue:
    scheme:
  segment:
    layout: col
    align:
  buttons:
    importance: secondary
    layout: row
  image:
    position:
    orientation:

_inputs:
