spec:
  structures:
    - content_blocks
  label: Services

blueprint:
  writeup:
  buttons:
  services:

config:
  section:
    align: start
    size:
  segment:
    layout: col
    align:
  buttons:
    importance:
    layout:
  image:
    position:
    orientation:

preview: