// Generated by ts-to-zod
import { z } from 'zod'

export const categoriesSchema = z.object({
  title: z.string().optional().nullable(),
  description: z.string().optional().nullable(),
  image: z.object({
    src: z.string().optional().nullable(),
    alt: z.string().optional().nullable(),
  }),
  seo: z.object({
    title: z.string().optional().nullable(),
    description: z.string().optional().nullable(),
    image: z.object({
      src: z.string().optional().nullable(),
      alt: z.string().optional().nullable(),
    }),
  }),
})
