spec:
  structures:
    - feature
    - features
  label: Feature

blueprint:
  visual:
  writeup:
  buttons:

preview:
  image:  
    src: https://via.placeholder.com/300x300
    alt: Lorem ipsum
  writeup: |
    <h1>Lorem ipsum</h1>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam, soluta.</p>
  buttons: 
    - label: Lorem ipsum
      href: '#'

config:
  card:
    frame: fill
    look:
    hue:
    scheme:
  image:
    position:
    ratio:
  group:
    importance: tertiary
    layout: