spec:
  structures:
    - announcement
  label: Announcement

blueprint:
  text: 

preview:
  text: Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus, incidunt. Quae, eos!

config:

_inputs:


