// Generated by ts-to-zod
import { z } from 'zod'

export const productsSchema = z.object({
  _stripe_product_id: z.string().nullable(),
  _stripe_price_id: z.string().nullable(),
  title: z.string().nullable(),
  description: z.string().nullable(),
  images: z.array(
    z.object({
      src: z.string().nullable(),
      alt: z.string().nullable(),
    })
  ),
  price: z.number().nullable(),
  categories: z.array(z.string()).nullable(),
  brand: z.string().nullable(),
  seo: z.object({
    title: z.string().nullable(),
    description: z.string().nullable(),
    image: z.object({
      src: z.string().nullable(),
      alt: z.string().nullable(),
    }),
  }),
})
