_schema: intro
title: My new intro.bookhsop
spec:
  structures:
    - content_blocks
  label: My new intro
blueprint:
  writeup:
preview:
  writeup: >-
    <h1>Lorem ipsum dolor sit</h1><p>Lorem ipsum dolor sit amet consectetur
    adipisicing elit. Suscipit, numquam!</p>
config:
  section:
    frame:
    look:
    size:
    hue:
    scheme:
  segment:
    layout:
    align:
_inputs:
