spec:
  structures:
    - content_blocks
  label: Categories

blueprint:
  writeup:
  buttons:

_inputs:
  blueprint:
    type: object
    options:
      subtype: mutable
      entries:
        allowed_keys:
          - writeup
          - buttons
          - categories
#