// Generated by ts-to-zod
import { z } from 'zod'

export const pagesSchema = z.object({
  blocks: z.any(),
  seo: z.object({
    title: z.string().nullable(),
    description: z.string().nullable(),
    image: z.object({
      src: z.string().nullable(),
      alt: z.string().nullable(),
    }),
  }),
})
