// Generated by ts-to-zod
import { z } from 'zod'

export const employeesSchema = z.object({
  name: z.string().nullable(),
  tagline: z.string().nullable(),
  description: z.string().nullable(),
  image: z.object({
    src: z.string().nullable(),
    alt: z.string().nullable(),
  }),
})
