spec:
  structures:
    - channels
  label: Channel

blueprint:
  key:
  value:

_inputs:
  key:
    label: Channel
    type: choice
    options:
      values:
        - email
        - phone
        - address
        - whatsapp

  value:
    label: Value
    type: string

preview:
