// Generated by ts-to-zod
import { z } from 'zod'

export const reviewsSchema = z.object({
  title: z.string().nullable(),
  description: z.string().nullable(),
  rating: z.number().nullable(),
  author: z.object({
    name: z.string().nullable(),
    tagline: z.string().nullable(),
    avatar: z.string().nullable(),
  }),
})
