_schema: cards
features:
  card:
    frame: fill
    look: ghost
    hue:
    scheme:
    class:
  image:
    position:
    orientation:
    class:
  segment:
    class:
offers:
  card:
    frame:
    look:
    hue:
    scheme:
    class:
  segment:
    class:
categories:
  card:
    frame:
    look:
    hue:
    scheme:
    class:
  image:
    position:
    orientation:
    class:
  segment:
    class:
persons:
  card:
    frame:
    look:
    hue:
    scheme:
    class:
  image:
    position:
    orientation:
    class:
  segment:
    class:
posts:
  card:
    frame:
    look:
    hue:
    scheme:
    class:
  image:
    position:
    orientation:
    class:
  segment:
    class:
products:
  card:
    frame: panel
    look: outline
    hue:
    scheme:
    class:
  image:
    position: cover
    orientation: landscape
    class:
  segment:
    class:
reviews:
  card:
    frame:
    look:
    hue:
    scheme:
    class:
  image:
    position:
    orientation:
    class:
  segment:
    class:
services:
  card:
    frame:
    look:
    hue:
    scheme:
    class:
  image:
    position:
    orientation:
    class:
  segment:
    class:

_inputs:
  frame:
    type: choice
    options:
      values:
        - panel
        - fill
  look:
    type: choice
    options:
      values:
        - surface
        - soft
        - outline
        - ghost
