_schema: contact

spec:
  structures:
    - content_blocks
  label: Contact

blueprint:
  writeup:
  channels:
  socials: 
  form:

preview:
  writeup: |
    <h1>Lorem ipsum dolor sit</h1>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Suscipit, numquam!</p>
  channels:
    - email
    - phone
    - whatsapp
    - address
  socials:
    - facebook
    - instagram
    - twitter
    - youtube
  form:

config:
  section:
    layout: row
    align:
    frame: 
    look:
    order:
    size: medium
    hue:
    scheme:
  channels: true
  socials: true
  segment:
    layout: col
    align:
    class: max-w-xl
  group:
    layout: col

_inputs:
