spec:
  structures:
    - content_blocks
  label: Cta

blueprint:
  writeup:
  buttons:
  button:

preview:
  writeup: |
    <h2>Lorem ipsum dolor sit</h2>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Suscipit, numquam!</p>
  buttons:
    - label: Lorem ipsum
      href: '#'
    - label: Lorem ipsum
      href: '#'

config:
  section:
    frame: panel
    look: soft
    size:
    hue: brand
    scheme: dark
  segment:
    layout: row
    align: center
  group:
    layout: col
    importance: secondary
  button: