spec:
  structures:
    - content_blocks
  label: Features

blueprint:
  features:
    - image:
        src:
        alt:
      writeup:
      buttons:

preview:
  features:
    - image:  
        src: https://via.placeholder.com/300x300
        alt: Lorem ipsum
      writeup: |
        <h1>Lorem ipsum</h1>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam, soluta.</p>
      buttons: 
        - label: Lorem ipsum
          href: '#'
    - image:  
        src: https://via.placeholder.com/300x300
        alt: Lorem ipsum
      writeup: |
        <h1>Lorem ipsum</h1>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam, soluta.</p>
      buttons: 
        - label: Lorem ipsum
          href: '#'
    - image:  
        src: https://via.placeholder.com/300x300
        alt: Lorem ipsum
      writeup: |
        <h1>Lorem ipsum</h1>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam, soluta.</p>
      buttons: 
        - label: Lorem ipsum
          href: '#'

config:
  section:
    align: start
    frame: fill
    look:
    size:
    hue:
    scheme:
  segment:
    layout: col
    align: center
  buttons:
    importance: primary
    layout: row
  deck:
    layout: row
    size:

_inputs:
