_schema: hero
spec:
  structures:
    - content_blocks
  label: Hero
blueprint:
  writeup:
  buttons:
  image:
preview:
  writeup: >-
    <h1>Lorem ipsum dolor sit</h1><p>Lorem ipsum dolor sit amet consectetur
    adipisicing elit. Suscipit, numquam!</p>
  buttons:
    - _bookshop_name: elements/button
      label: Lorem ipsum
      href: '#'
    - _bookshop_name: elements/button
      label: Lorem ipsum
      href: '#'
  image:
    _bookshop_name: elements/image
    src: src/assets/uploads/lavis-bg-4 (Optimized).webp
    alt: Lorem ipsum dolor sit
config:
  section:
    layout: row
    align:
    frame: screen
    look:
    order:
    size: large
    hue:
    scheme:
  segment:
    layout: row
    align: center
  group:
    importance: primary
    layout: col
  image:
    position: background
    orientation: landscape
_inputs:
