_schema: offers

spec:
  structures:
    - content_blocks
  label: Offers

blueprint:
  writeup:
  offers:
    - _card_name: offers
      icon:
      writeup:
      buttons:

preview:
  writeup: |
    <h2>Lorem ipsum dolor sit</h2>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Suscipit, numquam!</p>
  offers:
    - writeup: |
        <p>Lorem ipsum dolor</p>
        <h1>Lorem ipsum</h1>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam, soluta.</p>
      specs:
        - Lorem ipsum dolor sit
        - Lorem ipsum dolor sit
        - Lorem ipsum dolor sit
        - Lorem ipsum dolor sit
        - Lorem ipsum dolor sit
      buttons: 
        - label: Lorem ipsum
          href: '#'
        - label: Lorem ipsum
          href: '#'
    - writeup: |
        <p>Lorem ipsum dolor</p>
        <h1>Lorem ipsum</h1>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam, soluta.</p>
      specs:
        - Lorem ipsum dolor sit
        - Lorem ipsum dolor sit
        - Lorem ipsum dolor sit
        - Lorem ipsum dolor sit
        - Lorem ipsum dolor sit
      buttons: 
        - label: Lorem ipsum
          href: '#'
        - label: Lorem ipsum
          href: '#'
    - writeup: |
        <p>Lorem ipsum dolor</p>
        <h1>Lorem ipsum</h1>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam, soluta.</p>
      specs:
        - Lorem ipsum dolor sit
        - Lorem ipsum dolor sit
        - Lorem ipsum dolor sit
        - Lorem ipsum dolor sit
        - Lorem ipsum dolor sit
      buttons: 
        - label: Lorem ipsum
          href: '#'
        - label: Lorem ipsum
          href: '#'

config:
  section:
    layout: row
    align: center
    size:
    order:
  segment:
    align:
  deck:
    layout: row
    size:

_inputs:
  specs:
    type: array