spec:
  structures:
    - content_blocks
  label: Highlights

blueprint:
  highlights:
    - _card_name: offers
      image:
      writeup:
      buttons:

preview:
  highlights:
    - image:
        src: https://picsum.photos/seed/picsum/1600/900
        alt: Lorem ipsum dolor sit
      writeup: |
        <h1>Lorem ipsum</h1>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam, soluta.</p>
      buttons: 
        - label: Lorem ipsum
          href: '#'
    - image:
        src: https://picsum.photos/seed/picsum/1600/900
        alt: Lorem ipsum dolor sit
      writeup: |
        <h1>Lorem ipsum</h1>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam, soluta.</p>
      buttons: 
        - label: Lorem ipsum
          href: '#'
    - image:
        src: https://picsum.photos/seed/picsum/1600/900
        alt: Lorem ipsum dolor sit
      writeup: |
        <h1>Lorem ipsum</h1>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam, soluta.</p>
      buttons: 
        - label: Lorem ipsum
          href: '#'

config:
  section:
    align: start
    frame: fill
    look:
    size:
    hue:
    scheme:
  segment:
    layout: col
    align:
  group:
    importance: primary
    layout: row
  deck:
    layout: row
    size: