spec:
  structures:
    - socials
    - social
  label: Social

blueprint:
  key:

preview:
  key: facebook
  
config:
  look: solid
  hue: brand
  class:

_inputs:  
  key:
    type: choice
    options:
      values:
        - facebook 
        - twitter
        - instagram
        - pinterest
        - linkedin
        - youtube
        - tiktok
        - snapchat